name: Open-Wrt-Lean-CI

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: Build OpenWrt
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Checkout Lean
        uses: actions/checkout@v2
        with:
          repository: coolsnowwolf/lede
          path: lede
      - name: Compile firmware
        run: |
          ls
          find . -name "Makefile"
