name: Open-Wrt-Lean-CI

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-18.04
    steps:
      - name: Hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Bo Wang'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
